primary_region = 'lhr'

[build]
  builder = "paketobuildpacks/builder:base"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
